
package com.commnetsoft.api.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OrgAndUserServicePortType", targetNamespace = "http://webservice.api.commnetsoft.com")
public interface OrgAndUserServicePortType {

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param userid
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserInfoById", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserInfoById")
	@ResponseWrapper(localName = "getUserInfoByIdResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserInfoByIdResponse")
	public String getUserInfoById(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "userid", targetNamespace = "http://webservice.api.commnetsoft.com") String userid,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param password
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "valpassword", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.Valpassword")
	@ResponseWrapper(localName = "valpasswordResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.ValpasswordResponse")
	public String valpassword(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "password", targetNamespace = "http://webservice.api.commnetsoft.com") String password,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param loginname
	 * @param nation
	 * @param datatype
	 * @param mobilephone
	 * @param idcard
	 * @param sex
	 * @param sign
	 * @param time
	 * @param username
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "syncUserExt", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.SyncUserExt")
	@ResponseWrapper(localName = "syncUserExtResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.SyncUserExtResponse")
	public String syncUserExt(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "loginname", targetNamespace = "http://webservice.api.commnetsoft.com") String loginname,
			@WebParam(name = "mobilephone", targetNamespace = "http://webservice.api.commnetsoft.com") String mobilephone,
			@WebParam(name = "idcard", targetNamespace = "http://webservice.api.commnetsoft.com") String idcard,
			@WebParam(name = "username", targetNamespace = "http://webservice.api.commnetsoft.com") String username,
			@WebParam(name = "sex", targetNamespace = "http://webservice.api.commnetsoft.com") String sex,
			@WebParam(name = "nation", targetNamespace = "http://webservice.api.commnetsoft.com") String nation,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param describe
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "deleteOrg", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.DeleteOrg")
	@ResponseWrapper(localName = "deleteOrgResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.DeleteOrgResponse")
	public String deleteOrg(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype,
			@WebParam(name = "describe", targetNamespace = "http://webservice.api.commnetsoft.com") String describe);

	/**
	 * 
	 * @param args
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getSsoUserByMap", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetSsoUserByMap")
	@ResponseWrapper(localName = "getSsoUserByMapResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetSsoUserByMapResponse")
	public String getSsoUserByMap(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "args", targetNamespace = "http://webservice.api.commnetsoft.com") String args,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param loginname
	 * @param datatype
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserInfo", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserInfo")
	@ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserInfoResponse")
	public String getUserInfo(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "loginname", targetNamespace = "http://webservice.api.commnetsoft.com") String loginname,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param mobilephone
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "checkphoneunique", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.Checkphoneunique")
	@ResponseWrapper(localName = "checkphoneuniqueResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.CheckphoneuniqueResponse")
	public String checkphoneunique(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "mobilephone", targetNamespace = "http://webservice.api.commnetsoft.com") String mobilephone,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param datatype
	 * @param scope
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserList", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserList")
	@ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserListResponse")
	public String getUserList(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "scope", targetNamespace = "http://webservice.api.commnetsoft.com") String scope,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param args
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param describe
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "synchronizeOrg", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.SynchronizeOrg")
	@ResponseWrapper(localName = "synchronizeOrgResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.SynchronizeOrgResponse")
	public String synchronizeOrg(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "args", targetNamespace = "http://webservice.api.commnetsoft.com") String args,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype,
			@WebParam(name = "describe", targetNamespace = "http://webservice.api.commnetsoft.com") String describe);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getOrgInfo", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetOrgInfo")
	@ResponseWrapper(localName = "getOrgInfoResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetOrgInfoResponse")
	public String getOrgInfo(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param loginname
	 * @param loginpwd
	 * @param datatype
	 * @param mobilephone
	 * @param sign
	 * @param encryptiontype
	 * @param time
	 * @param type
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "unbindmobile", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.Unbindmobile")
	@ResponseWrapper(localName = "unbindmobileResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.UnbindmobileResponse")
	public String unbindmobile(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "type", targetNamespace = "http://webservice.api.commnetsoft.com") String type,
			@WebParam(name = "mobilephone", targetNamespace = "http://webservice.api.commnetsoft.com") String mobilephone,
			@WebParam(name = "loginname", targetNamespace = "http://webservice.api.commnetsoft.com") String loginname,
			@WebParam(name = "encryptiontype", targetNamespace = "http://webservice.api.commnetsoft.com") String encryptiontype,
			@WebParam(name = "loginpwd", targetNamespace = "http://webservice.api.commnetsoft.com") String loginpwd,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param args
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param describe
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "synchronizeUser", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.SynchronizeUser")
	@ResponseWrapper(localName = "synchronizeUserResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.SynchronizeUserResponse")
	public String synchronizeUser(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "args", targetNamespace = "http://webservice.api.commnetsoft.com") String args,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype,
			@WebParam(name = "describe", targetNamespace = "http://webservice.api.commnetsoft.com") String describe);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param mapservicecode
	 * @param loginname
	 * @param datatype
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getMapUser", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetMapUser")
	@ResponseWrapper(localName = "getMapUserResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetMapUserResponse")
	public String getMapUser(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "mapservicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String mapservicecode,
			@WebParam(name = "loginname", targetNamespace = "http://webservice.api.commnetsoft.com") String loginname,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param loginname
	 * @param datatype
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserRole", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserRole")
	@ResponseWrapper(localName = "getUserRoleResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserRoleResponse")
	public String getUserRole(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "loginname", targetNamespace = "http://webservice.api.commnetsoft.com") String loginname,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param userid
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserRoleById", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserRoleById")
	@ResponseWrapper(localName = "getUserRoleByIdResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserRoleByIdResponse")
	public String getUserRoleById(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "userid", targetNamespace = "http://webservice.api.commnetsoft.com") String userid,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param loginname
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param describe
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "deleteUser", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.DeleteUser")
	@ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.DeleteUserResponse")
	public String deleteUser(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "loginname", targetNamespace = "http://webservice.api.commnetsoft.com") String loginname,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype,
			@WebParam(name = "describe", targetNamespace = "http://webservice.api.commnetsoft.com") String describe);

	/**
	 * 
	 * @param servicecode
	 * @param nation
	 * @param datatype
	 * @param sex
	 * @param sign
	 * @param time
	 * @param idnum
	 * @param username
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "valiidcard", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.Valiidcard")
	@ResponseWrapper(localName = "valiidcardResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.ValiidcardResponse")
	public String valiidcard(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "username", targetNamespace = "http://webservice.api.commnetsoft.com") String username,
			@WebParam(name = "idnum", targetNamespace = "http://webservice.api.commnetsoft.com") String idnum,
			@WebParam(name = "sex", targetNamespace = "http://webservice.api.commnetsoft.com") String sex,
			@WebParam(name = "nation", targetNamespace = "http://webservice.api.commnetsoft.com") String nation,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param mobilephone
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "regbymobile", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.Regbymobile")
	@ResponseWrapper(localName = "regbymobileResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.RegbymobileResponse")
	public String regbymobile(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "mobilephone", targetNamespace = "http://webservice.api.commnetsoft.com") String mobilephone,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param orgcoding
	 * @param servicecode
	 * @param datatype
	 * @param scope
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getSubOrg", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetSubOrg")
	@ResponseWrapper(localName = "getSubOrgResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetSubOrgResponse")
	public String getSubOrg(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "scope", targetNamespace = "http://webservice.api.commnetsoft.com") String scope,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

}
