
package com.commnetsoft.api.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "OrgAndUserService", targetNamespace = "http://webservice.api.commnetsoft.com", wsdlLocation = "http://puser.zjzwfw.gov.cn/sso/service/OrgAndUserService?wsdl")
public class OrgAndUserService extends Service {

	private final static URL ORGANDUSERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.commnetsoft.api.webservice.OrgAndUserService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.commnetsoft.api.webservice.OrgAndUserService.class.getResource(".");
			url = new URL(baseUrl, "http://puser.zjzwfw.gov.cn/sso/service/OrgAndUserService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://puser.zjzwfw.gov.cn/sso/service/OrgAndUserService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ORGANDUSERSERVICE_WSDL_LOCATION = url;
	}

	public OrgAndUserService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OrgAndUserService() {
		super(ORGANDUSERSERVICE_WSDL_LOCATION, new QName("http://webservice.api.commnetsoft.com", "OrgAndUserService"));
	}

	/**
	 * 
	 * @return returns OrgAndUserServicePortType
	 */
	@WebEndpoint(name = "OrgAndUserServiceHttpPort")
	public OrgAndUserServicePortType getOrgAndUserServiceHttpPort() {
		return super.getPort(new QName("http://webservice.api.commnetsoft.com", "OrgAndUserServiceHttpPort"),
				OrgAndUserServicePortType.class);
	}

}
