
package com.commnetsoft.api.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SimpleAuthServicePortType", targetNamespace = "http://webservice.api.commnetsoft.com")
public interface SimpleAuthServicePortType {

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "logout", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.Logout")
	@ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.LogoutResponse")
	public String logout(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "token", targetNamespace = "http://webservice.api.commnetsoft.com") String token,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserSys", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserSys")
	@ResponseWrapper(localName = "getUserSysResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserSysResponse")
	public String getUserSys(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "token", targetNamespace = "http://webservice.api.commnetsoft.com") String token,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserRole", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserRole")
	@ResponseWrapper(localName = "getUserRoleResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserRoleResponse")
	public String getUserRole(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "token", targetNamespace = "http://webservice.api.commnetsoft.com") String token,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param proxyapp
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "generateST", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GenerateST")
	@ResponseWrapper(localName = "generateSTResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GenerateSTResponse")
	public String generateST(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "proxyapp", targetNamespace = "http://webservice.api.commnetsoft.com") String proxyapp,
			@WebParam(name = "token", targetNamespace = "http://webservice.api.commnetsoft.com") String token,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param st
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "ticketValidation", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.TicketValidation")
	@ResponseWrapper(localName = "ticketValidationResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.TicketValidationResponse")
	public String ticketValidation(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "st", targetNamespace = "http://webservice.api.commnetsoft.com") String st,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserInfo", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserInfo")
	@ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserInfoResponse")
	public String getUserInfo(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "token", targetNamespace = "http://webservice.api.commnetsoft.com") String token,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param orgcoding
	 * @param password
	 * @param servicecode
	 * @param loginname
	 * @param datatype
	 * @param sign
	 * @param encryptiontype
	 * @param time
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "idValidation", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.IdValidation")
	@ResponseWrapper(localName = "idValidationResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.IdValidationResponse")
	public String idValidation(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "loginname", targetNamespace = "http://webservice.api.commnetsoft.com") String loginname,
			@WebParam(name = "orgcoding", targetNamespace = "http://webservice.api.commnetsoft.com") String orgcoding,
			@WebParam(name = "encryptiontype", targetNamespace = "http://webservice.api.commnetsoft.com") String encryptiontype,
			@WebParam(name = "password", targetNamespace = "http://webservice.api.commnetsoft.com") String password,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

	/**
	 * 
	 * @param servicecode
	 * @param datatype
	 * @param sign
	 * @param time
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.api.commnetsoft.com")
	@RequestWrapper(localName = "getUserExt", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserExt")
	@ResponseWrapper(localName = "getUserExtResponse", targetNamespace = "http://webservice.api.commnetsoft.com", className = "com.commnetsoft.api.webservice.GetUserExtResponse")
	public String getUserExt(
			@WebParam(name = "servicecode", targetNamespace = "http://webservice.api.commnetsoft.com") String servicecode,
			@WebParam(name = "time", targetNamespace = "http://webservice.api.commnetsoft.com") String time,
			@WebParam(name = "sign", targetNamespace = "http://webservice.api.commnetsoft.com") String sign,
			@WebParam(name = "token", targetNamespace = "http://webservice.api.commnetsoft.com") String token,
			@WebParam(name = "datatype", targetNamespace = "http://webservice.api.commnetsoft.com") String datatype);

}
